name: 'coblocks'

config-version: 2
version: '0.1'

profile: 'coblocks'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

models:
  blocks:
    materialized: table
    staging:
      materialized: view
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'
