coblocks:
  target: dev
  outputs:
    prod:
      type: duckdb
      path: coblocks.duckdb
      remote:
        host: "{{ env_var('COBLOCKS_WAREHOUSE_HOST') }}"
        port: 5433
        user: "{{ env_var('COBLOCKS_WAREHOUSE_USER') }}"
      threads: 4

    dev: 
      type: duckdb
      path: coblocks.duckdb
      threads: 4