coblocks:
  target: "{{ env_var('COBLOCKS_DBT_PROFILE_TARGET') }}"
  outputs:
    remote:
      type: duckdb
      path: coblocks.duckdb
      remote:
        host: "{{ env_var('COBLOCKS_WAREHOUSE_HOST') }}"
        port: 5433
        user: "{{ env_var('COBLOCKS_WAREHOUSE_USER') }}"
      threads: 4

    local: 
      type: duckdb
      path: coblocks.duckdb
      threads: 4