coblocks:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: coblocks.duckdb
      remote:
        host: 0.0.0.0
        port: 5433
        user: postgres
      threads: 4

    dev: 
      type: duckdb
      path: coblocks.duckdb
      threads: 4